project:
  output-dir: ../docs

bibliography: references.bib
csl: ../assets/frontiers.csl

format:
  revealjs: 
    theme: [default, ../assets/slides.scss]
    slide-number: true
    html-math-method: katex
    chalkboard: 
      buttons: false
      theme: whiteboard

    revealjs-plugins:
      - pointer

title-slide-attributes:
    data-background-image: "img/tuc.svg"
    data-background-size: 30%
    data-background-opacity: "1"
    data-background-position: top

highlight-style: github
code-line-numbers: false
callout-appearance: minimal

filters:
  - ../assets/center_images.lua
  - quarto